# -*- coding: utf-8 -*-
"""Proyecto_Final_Diplomado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10z_D8Tj46QfFNWzv1gzkJlOwp4K-ZBAH

**Proyecto Final de Diplomado en Machine Learning y Deep Learning Aplicado**

Nombre: Predictor de Compras de Materiales

Datos: Informacion de Compras Publicas

Etapas del Proceso

1.   Limpieza de los datos recuperados
2.   Verificacion de la estructura de los datos
3.   Filtrar por informacion util
4.   Construccion de Modelo de Regresion

Etapa del modelado ML

1. Analisis Exploratorio
2. Empleo de estategia de Modelo de Regresion
3. Evaluacion de rendimiento
4. Proximas etapas
"""

try:
  from google.colab import drive
  drive.mount('/content/drive/')
  DATA_DIR='/content/drive/MyDrive/Diplomado/Proyecto_Final/contratos'
except ModuleNotFoundError:
  DATA_DIR='.'

print('Entorno OK!')

"""Luego de recuperado los archivos, deben obtenerse la relaciones entre si para unificar los procesos.
Existe una relacion entre si teniendo la primera columna relacionada entre los archivos.
Tambien existen referencias dentro de cada archivo a considerar para poder obtener los valores necesarios para el caso de estudio.
Cargar los registros y limpiar uno por uno para generar el dataset de entrenamiento.
"""

# Ejecutar esta celda primero: carga las tablas
import os
import pandas as pd
YEAR_LEN = 4
df_res = []

for ruta_actual, subdirectorios, archivos in os.walk(DATA_DIR):
  tiene_archivos = any(archivo.endswith('.csv') for archivo in archivos)

  if tiene_archivos:
    # Actualizamos la variable con la última carpeta encontrada
    print(f'Carpeta actual: {ruta_actual}')

    year = ruta_actual[-YEAR_LEN:]
    #print(year)
    for archivo in archivos:
        print(f' - Archivo: {archivo}')

    # leemos los archivos
    contrato = pd.read_csv(ruta_actual+"/parties.csv")
    items = pd.read_csv(ruta_actual+"/awa_items.csv")
    print("Contratos (partes):", len(contrato))
    print("Items de contratos:", len(items))

    #filtramos los datos importantes por un criterio
    criterio1 = contrato['compiledRelease/parties/0/identifier/legalName'].str.contains('(ANDE)', case=False, na=False)
    criterio2 = contrato['compiledRelease/parties/0/roles'].str.contains('buyer', case=False, na=False)

    contratos_ande = contrato[criterio1 & criterio2]

    # Extraemos columnas especificas de cada dataframe del csv
    columns_to_extract = ["compiledRelease/id", "compiledRelease/parties/0/name"]
    contratos_selected = contratos_ande[columns_to_extract]

    #columns_to_extract2 = ["compiledRelease/id", "compiledRelease/awards/0/items/0/description", "compiledRelease/awards/0/items/0/quantity", "compiledRelease/awards/0/items/0/unit/name", "compiledRelease/awards/0/items/0/unit/value/amount","compiledRelease/awards/0/items/0/unit/value/currency"]
    columns_to_extract2 = ["compiledRelease/id", "compiledRelease/awards/0/items/0/classification/description", "compiledRelease/awards/0/items/0/quantity", "compiledRelease/awards/0/items/0/unit/name", "compiledRelease/awards/0/items/0/unit/value/amount","compiledRelease/awards/0/items/0/unit/value/currency"]
    items_selected = items[columns_to_extract2]
    mixed_items_contracts = pd.merge(contratos_selected, items_selected, on='compiledRelease/id', how='inner')

    mixed_items_contracts["compiledRelease/year"] = year

    df_res.append(mixed_items_contracts)

final_res = pd.concat(df_res)
print("Listo.")

"""Una vez obteniendo los valores realizamos el filtro de los items mas relevantes"""

print("Items de contratos:", len(final_res))
final_res.sample(5)

"""Guardamos el parcial del analisis para avanzar con consultas sobre el archivo si se requiere."""

final_res.to_csv(DATA_DIR+'/file_filtered_merged.csv')

"""A partir de los datos obtenidos aplicamos filtros para retirar campos que no revisten utilidad y profundizar el analisis de los datos obtenidos y cuales corresponden a nuestro objeto de estudio."""

datased_cleared = final_res.copy()
dataset_cleared = datased_cleared.drop(['compiledRelease/id', 'compiledRelease/parties/0/name'], axis=1)
dataset_cleared.rename(columns={'compiledRelease/awards/0/items/0/classification/description': 'item', 'compiledRelease/awards/0/items/0/quantity': 'quantity',
                                'compiledRelease/awards/0/items/0/unit/name': 'unidad_medida','compiledRelease/awards/0/items/0/unit/value/amount': 'amount',
                                'compiledRelease/awards/0/items/0/unit/value/currency': 'currency', 'compiledRelease/year': 'year'}, inplace=True)

"""Una vez obtenido los resultados, verificamos"""

dataset_cleared.head()

print("Items de contratos de ANDE:", len(dataset_cleared))

"""Verificamos cuales son los tipo de items solicitados y solo para retener aquellos mas recurrentes"""

items_mas_pedidos = dataset_cleared["item"].value_counts() #("quantity")
items_mas_pedidos.head(50)

"""Es muy vago y requiere profundidad en un solo objeto"""

mask1 = dataset_cleared['item'].str.contains('Transformador de distribucion', case=False, na=False)
mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Ampliacion de red electrica', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Servicio desmontaje y montaje de Sistemas electricos de Sub estaciones', case=False, na=False)

transformadores_ande = dataset_cleared[mask1 & mask2]
transformadores_ande.sample(10)

#ordenar
transformadores_ande = transformadores_ande.sort_values(by=["year", "item"])

print("Cantidad de registros de transformadores contratos de ANDE:", len(transformadores_ande))

"""Tratar de obtener el grafico de todo lo obtenido"""

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(transformadores_ande["year"], transformadores_ande["quantity"], s=8)
plt.xlabel("Compras de Transformadores de los anhos 2016-2026 (Year)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(transformadores_ande["amount"], transformadores_ande["quantity"], s=8)
plt.xlabel("Compras de Transformadores en montos de los anhos 2016-2026 (Year)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

# Completar aquí
n_faltantes = transformadores_ande["quantity"].isna().sum()
print("Cantidad de registros faltantes en la columna 'quantity':", n_faltantes)

transformadores_ande.head()

"""Existen muchos valores con cantidades superiores a 3000"""

#mayores_cantidades = transformadores_ande[transformadores_ande["amount"] > 40000]
#print("Cantidad de registros con cantidades superiores a 3000:", len(mayores_cantidades))
#mayores_cantidades.head()

"""Con la informacion obtenida, retiramos los valores para visualizar el cambio"""

#mask1 = dataset_cleared['item'].str.contains('Transformador', case=False, na=False)
#mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)

#transformadores_ande = dataset_cleared[mask1 & mask2]
#transformadores_ande = transformadores_ande[transformadores_ande["quantity"] <= 3000]
#transformadores_ande = transformadores_ande[transformadores_ande["quantity"] < 2]

transformadores_grouped = transformadores_ande.groupby(['item', 'year', 'currency'])['quantity'].sum().reset_index()
transformadores_grouped.head()

"""Primer intento:
Generar un modelo de regresion para los datos reorganizados.
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


print("✓ Dataset: ", len(transformadores_grouped) ," filas cargadas.")
y = transformadores_grouped["quantity"]
X = transformadores_grouped[["year"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Predicciones con lo que haya
#años_futuros = np.array([[2027], [2028]])
y_pred = modelo.predict(X_test)


# evaluamos
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("===== MÉTRICAS DEL MODELO =====")
print(f"MAE  (Error Absoluto Medio): {mae:.3f}")
print(f"RMSE (Raíz del Error Cuadrático Medio): {rmse:.3f}")
print(f"R²   (Coeficiente de Determinación): {r2:.3f}")

"""Agregar una validacion pero considerando que tenemos pocos registros... puede ser bajo el rendimiento en especifico para el test"""

from sklearn.model_selection import cross_val_score

# Completar aquí
notas = cross_val_score(LinearRegression(), X, y, cv=5)
print(notas)

nota_honesta = round(notas.mean(), 2)

"""Intentamos realizar una prediccion tal cual hemos entrenamos"""