# -*- coding: utf-8 -*-
"""Proyecto_Final_Diplomado_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StKkN3l3MmbCgNZAhg4oRumhrmOIZVok

**Proyecto Final de Diplomado en Machine Learning y Deep Learning Aplicado**

Nombre: Predictor de Compras de Materiales

Datos: Información de Compras Publicas

Etapas del Proceso

1.   Limpieza de los datos recuperados
2.   Verificación de la estructura de los datos
3.   Filtrar por informacion útil
4.   Construcción de Modelo de Regresión

Etapa del modelado ML

1. Analisis Exploratorio
2. Empleo de estategia de Modelo de Regresion
3. Evaluacion de rendimiento
4. Proximas etapas
"""

try:
  from google.colab import drive
  drive.mount('/content/drive/')
  DATA_DIR='/content/drive/MyDrive/Diplomado/Proyecto_Final/contratos'
except ModuleNotFoundError:
  DATA_DIR='.'

print('Entorno OK!')

"""Luego de recuperado los archivos, deben obtenerse la relaciones entre si para unificar los procesos.
Existe una relacion entre si teniendo la primera columna relacionada entre los archivos.
Tambien existen referencias dentro de cada archivo a considerar para poder obtener los valores necesarios para el caso de estudio.
Cargar los registros y limpiar uno por uno para generar el dataset de entrenamiento.
"""

# Ejecutar esta celda primero: carga las tablas
import os
import pandas as pd
YEAR_LEN = 4
#df_res = []

for ruta_actual, subdirectorios, archivos in os.walk(DATA_DIR):
  tiene_archivos = any(archivo.endswith('.csv') for archivo in archivos)

  if tiene_archivos:
    # Actualizamos la variable con la última carpeta encontrada
    print(f'Carpeta actual: {ruta_actual}')

    year = ruta_actual[-YEAR_LEN:]
    #print(year)
    for archivo in archivos:
        print(f' - Archivo: {archivo}')

    # leemos los archivos
    contrato = pd.read_csv(ruta_actual+"/parties.csv")
    items = pd.read_csv(ruta_actual+"/awa_items.csv")
    detalles_adj = pd.read_csv(ruta_actual+"/awards.csv")
    print("Adjudicacion (partes):", len(contrato))
    print("Adjudicacion (detalles):", len(detalles_adj))
    print("Items de contratos:", len(items))

    name_filtered_generic = 'data_merged_' + year + '.csv'

    #filtramos los datos importantes por un criterio
    criterio1 = contrato['compiledRelease/parties/0/identifier/legalName'].str.contains('(ANDE)', case=False, na=False)
    criterio2 = contrato['compiledRelease/parties/0/roles'].str.contains('buyer', case=False, na=False)
    contratos_ande = contrato[criterio1 & criterio2]

    # Extraemos columnas especificas de cada dataframe del csv
    columns_to_extract = ["compiledRelease/id", "compiledRelease/parties/0/name"]
    contratos_selected = contratos_ande[columns_to_extract]

    columns_to_extract2 = ["compiledRelease/id", "compiledRelease/awards/0/date"]
    awards_details_selected = detalles_adj[columns_to_extract2]

    # Convert join keys to category
    contratos_selected["compiledRelease/id"] = contratos_selected["compiledRelease/id"].astype('category')
    awards_details_selected["compiledRelease/id"] = awards_details_selected["compiledRelease/id"].astype('category')

    # Merge with better performance
    mixed_awards_contracts = pd.merge(contratos_selected, awards_details_selected, on='compiledRelease/id', how='left')
    mixed_awards_contracts["compiledRelease/year_compiled"] = year

    # deleting dfs to save memory
    del(contrato)
    del(contratos_ande)
    del(contratos_selected)
    del(awards_details_selected)
    del(detalles_adj)

    #items_filtered = items_selected[items_selected.index.isin()]
    # Process logs in chunks
    #for chunk in pd.read_csv(ruta_actual+"/awa_items.csv", chunksize=500_000):
        #columns_to_extract3 = ["compiledRelease/id", "compiledRelease/awards/0/items/0/classification/description", "compiledRelease/awards/0/items/0/quantity", "compiledRelease/awards/0/items/0/unit/value/amount","compiledRelease/awards/0/items/0/unit/value/currency"]
        #items_selected = chunk[columns_to_extract3]
        #items_selected["compiledRelease/id"] = items_selected["compiledRelease/id"].astype('category')
        # merge the columns
        #mixed_items_contracts = pd.merge(mixed_awards_contracts, items_selected, on='compiledRelease/id', how='left')

    #Process in the same
    columns_to_extract3 = ["compiledRelease/id", "compiledRelease/awards/0/items/0/classification/description", "compiledRelease/awards/0/items/0/quantity", "compiledRelease/awards/0/items/0/unit/value/amount","compiledRelease/awards/0/items/0/unit/value/currency"]
    items_selected = items[columns_to_extract3]
    items_selected["compiledRelease/id"] = items_selected["compiledRelease/id"].astype('category')
    # merge the columns
    mixed_items_contracts = pd.merge(mixed_awards_contracts, items_selected, on='compiledRelease/id', how='inner')

    mixed_items_contracts.to_csv(ruta_actual+'/'+name_filtered_generic)

    # deleting dfs to save memory
    del(items)
    del(items_selected)
    del(mixed_awards_contracts)
    del(mixed_items_contracts)

    #df_res.append(mixed_items_contracts)

#final_res = pd.concat(df_res)
print("Listo. Archivos procesados")

"""Luego de procesar por año los conjugamos en uno sólo para reunir los valores"""

df_res = []

for ruta_actual, subdirectorios, archivos in os.walk(DATA_DIR):
  tiene_archivos = any(archivo.endswith('.csv') for archivo in archivos)

  if tiene_archivos:
    # Actualizamos la variable con la última carpeta encontrada -> name_filtered_generic = 'data_merged_' + year + '.csv'
    print(f'Carpeta actual: {ruta_actual}')
    year = ruta_actual[-YEAR_LEN:]
    name_filtered_generic = 'data_merged_' + year + '.csv'

    # leemos los archivos
    adj_contratos = pd.read_csv(ruta_actual+"/"+name_filtered_generic)
    print("Items de contratos:", len(adj_contratos))

    df_res.append(adj_contratos)

final_res = pd.concat(df_res)
print("Listo. Archivos listo para continuar con análisis.")

"""Una vez obteniendo los valores realizamos el filtro de los items mas relevantes"""

print("Items de contratos:", len(final_res))
final_res.sample(5)

"""Guardamos el parcial del analisis para avanzar con consultas sobre el archivo si se requiere."""

final_res.to_csv(DATA_DIR+'/file_filtered_merged.csv')

"""A partir de los datos obtenidos aplicamos filtros para retirar campos que no revisten utilidad y profundizar el analisis de los datos obtenidos y cuales corresponden a nuestro objeto de estudio."""

#mask1 = final_res['compiledRelease/parties/0/name'].str.contains(' (ANDE)', case=False, na=False)
mask1 = final_res['compiledRelease/parties/0/name'].str.contains('Administración Nacional de Electricidad', case=False, na=False)

datased_cleared = final_res[mask1]

print("Items de contratos - Solo Ande:", len(datased_cleared))
datased_cleared.sample(5)

"""Solamente obtenemos los datos relevantes para mantener un dataset consistente. Para evitar ambigüedad en el filtro anterior sólo retuvimos datos de una entidad"""

#datased_cleared = final_res.copy()
dataset_cleared = datased_cleared.drop(['compiledRelease/id', 'compiledRelease/parties/0/name', 'Unnamed: 0'], axis=1)
dataset_cleared.rename(columns={'compiledRelease/awards/0/items/0/classification/description': 'item', 'compiledRelease/awards/0/items/0/quantity': 'quantity',
                                 'compiledRelease/awards/0/date': 'date_awards','compiledRelease/awards/0/items/0/unit/value/amount': 'amount',
                                'compiledRelease/awards/0/items/0/unit/value/currency': 'currency', 'compiledRelease/year_compiled': 'year_compiled'}, inplace=True)

"""Una vez obtenido los resultados, verificamos"""

print(dataset_cleared.columns)
dataset_cleared.head()

print("Items de contratos de ANDE:", len(dataset_cleared))

"""Verificamos cuales son los tipo de items solicitados y solo para retener aquellos mas recurrentes"""

items_mas_pedidos = dataset_cleared["item"].value_counts() #("quantity")
items_mas_pedidos.head(20)

# Agrupar por año e ítem, y sumar las cantidades
#items_grouped = (dataset_cleared.groupby(["year_compiled", "item"], as_index=False)["quantity"].sum())
items_grouped = (dataset_cleared.groupby(["year_compiled", "item"]).size().reset_index(name="order_count"))

# Obtener el ítem más pedido por cada año
#top_items = items_grouped.loc[items_grouped.groupby("year_compiled")["quantity"].idxmax()]
top_items_by_freq = items_grouped.loc[items_grouped.groupby("year_compiled")["order_count"].idxmax()].head(10)

print(top_items_by_freq)

import matplotlib.pyplot as plt

# Contar la cantidad de pedidos por item (ajustá 'item' y 'quantity' a tus columnas reales)
top_items_by_freq = dataset_cleared.groupby('item')['quantity'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 6))
plt.barh(top_items_by_freq.index, top_items_by_freq.values, color='steelblue')
plt.xlabel('Cantidad total pedida')
plt.ylabel('Item')
plt.title('Top 10 items más pedidos')
plt.gca().invert_yaxis()  # Para que el más pedido quede arriba
plt.tight_layout()
plt.show()

import numpy as np

resumen = dataset_cleared.groupby('item').agg(cantidad=('quantity', 'sum'), monto=('amount', 'sum')).sort_values('cantidad', ascending=False).head(10)

fig, ax1 = plt.subplots(figsize=(10, 6))

x = np.arange(len(resumen))
width = 0.4

ax1.barh(x - width/2, resumen['cantidad'], height=width, color='steelblue', label='Cantidad')
ax1.set_yticks(x)
ax1.set_yticklabels(resumen.index)
ax1.invert_yaxis()
ax1.set_xlabel('Cantidad')

ax2 = ax1.twiny()
ax2.barh(x + width/2, resumen['monto'], height=width, color='darkorange', label='Monto (PYG)')
ax2.set_xlabel('Monto (PYG)')

fig.legend(loc='upper right', bbox_to_anchor=(0.9, 0.9))
plt.title('Top 10 items: Cantidad vs. Monto')
plt.tight_layout()
plt.show()

import numpy as np

# Pivotea: filas = item, columnas = year, valores = cantidad
tabla = dataset_cleared.pivot_table(index='item', columns='year_compiled', values='quantity', aggfunc='sum', fill_value=0)

# Tomamos los top 10 items según el total general
top_items = tabla.sum(axis=1).sort_values(ascending=False).head(5).index
tabla = tabla.loc[top_items]

tabla.plot(kind='barh', figsize=(10, 7))
plt.xlabel('Cantidad')
plt.ylabel('Item')
plt.title('Cantidad por item y año')
plt.legend(title='Año')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""Es muy vago y requiere profundidad en un solo objeto"""

mask1 = dataset_cleared['item'].str.contains('Transformador de distribucion', case=False, na=False)
mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Ampliacion de red electrica', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Servicio desmontaje y montaje de Sistemas electricos de Sub estaciones', case=False, na=False)

transformadores_ande = dataset_cleared[mask1 & mask2]
transformadores_ande.sample(10)

#ordenar
transformadores_ande = transformadores_ande.sort_values(by=["year_compiled", "item"])

print("Cantidad de registros de transformadores contratos de ANDE:", len(transformadores_ande))

"""Tratar de obtener el grafico de todo lo obtenido"""

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(transformadores_ande["year_compiled"], transformadores_ande["quantity"], s=8)
plt.xlabel("Compras de Transformadores de los anhos 2016-2026 (Year_Compiled)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(transformadores_ande["amount"], transformadores_ande["quantity"], s=8)
plt.xlabel("Compras de Transformadores en montos de los anhos 2016-2025 (Year_Compiled)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

# Completar aquí
n_faltantes = transformadores_ande["quantity"].isna().sum()
print("Cantidad de registros faltantes en la columna 'quantity':", n_faltantes)

transformadores_ande.head()

"""Existen muchos valores con cantidades superiores a 3000

Con la informacion obtenida, retiramos los valores para visualizar el cambio
"""

#mask1 = dataset_cleared['item'].str.contains('Transformador', case=False, na=False)
#mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)

#transformadores_ande = dataset_cleared[mask1 & mask2]
#transformadores_ande = transformadores_ande[transformadores_ande["quantity"] <= 3000]
#transformadores_ande = transformadores_ande[transformadores_ande["quantity"] < 2]

transformadores_grouped = transformadores_ande.groupby(['item', 'year_compiled', 'currency'])['quantity'].sum().reset_index()
transformadores_grouped.head()

"""Primer intento:
Generar un modelo de regresion para los datos reorganizados.
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


print("✓ Dataset: ", len(transformadores_grouped) ," filas cargadas.")
y = transformadores_grouped["quantity"]
X = transformadores_grouped[["year_compiled"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

"""Generamos una pequeña evaluación con datos de test para validar el proceso"""

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Predicciones con lo que haya
# Crear DataFrame con el mismo nombre de columna que X_train
#X_nuevo = pd.DataFrame({"year_compiled": [2026, 2027, 2028]})
y_pred = modelo.predict(X_test)


# evaluamos
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("===== MÉTRICAS DEL MODELO =====")
print(f"MAE  (Error Absoluto Medio): {mae:.3f}")
print(f"RMSE (Raíz del Error Cuadrático Medio): {rmse:.3f}")
print(f"R²   (Coeficiente de Determinación): {r2:.3f}")

"""Verificamos la gráfica para visibilizar el proceso"""

plt.figure(figsize=(8, 6))
plt.scatter(y_test, modelo.predict(X_test), color='teal', alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='red', linestyle='--', label='Predicción establecida sobre test')
plt.xlabel('Valor real')
plt.ylabel('Valor predicho')
plt.title('Predicción vs. Valor real')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""Agregar una validacion pero considerando que tenemos pocos registros... puede ser bajo el rendimiento en especifico para el test"""

from sklearn.model_selection import cross_val_score

# Completar aquí
notas = cross_val_score(LinearRegression(), X, y, cv=5)
print(notas)

nota_honesta = round(notas.mean(), 2)

"""De lo evaluado y con los datos, es muy posible que se tenga muy poco aprendizaje en base al resumen de los datos y las bajas calificaciones.

## Segundo Round:
- Ya hemos probado validez con los datos, pero tomemos el ítem de mayor volumen de pedidos
- Arriesguemos tomando los datos de las fechas más largas en el detalle
- Incluso empleemos eso como dato para el año o sólo esa fecha para el modelo
"""

mask1 = dataset_cleared['item'].str.contains('Cable', case=False, na=False)
mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
mask3 = ~dataset_cleared['item'].str.contains('Montaje', case=False, na=False)
mask4 = ~dataset_cleared['item'].str.contains('Terminación', case=False, na=False)

cables_ande = dataset_cleared[mask1 & mask2 & mask3 & mask4]
cables_ande.sample(10)

"""Como se visibiliza hay muchos datos de fecha con tiempo y no estructura normalizada que debería formatearse."""

# Crear la nueva columna con formato DD-MM-AAAA
#cables_ande['date_process'] = pd.to_datetime(cables_ande['date_awards'], errors='coerce').dt.date
#cables_ande_grouped = cables_ande.groupby(['item', 'year_compiled', 'currency', 'date_process'])['quantity'].sum().reset_index()

#ordenar
#cables_ande_grouped = cables_ande_grouped.sort_values(by=["date_process", "item"])
#cables_ande_grouped ['date_process'] = cables_ande_grouped ['date_process'].apply(pd.Timestamp.timestamp)

#Y usar year_frac en vez de (o además de) year_compiled, ya que:
#Es continua (mejor para regresión lineal que categorías discretas)
#Captura la tendencia temporal real, no solo el año "compilado"
#Si agrupás por year_frac con más granularidad (por trimestre, por ejemplo), podés ver tendencias intra-año

cables_ande['date_awards'] = pd.to_datetime(cables_ande['date_awards'])
#cables_ande['year_extracted'] = cables_ande['date_awards'].dt.year
cables_ande['year_frac'] = cables_ande['date_awards'].dt.year + (cables_ande['date_awards'].dt.dayofyear - 1) / 365
cables_ande_grouped = cables_ande.groupby(['item', 'year_frac', 'currency', 'date_awards'])['quantity'].sum().reset_index()
cables_ande_grouped.head()
cables_ande_grouped = cables_ande_grouped.sort_values(by=["year_frac", "item"])

print("Cantidad de registros de cables en contratos de ANDE:", len(cables_ande_grouped))

cables_ande_grouped.head()

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(cables_ande_grouped["year_frac"], cables_ande_grouped["quantity"], s=8)
plt.xlabel("Compras de Cables de los anhos 2016-2026 (Year_Compiled)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

cables_ande_grouped = cables_ande_grouped[cables_ande_grouped["quantity"] <= 5000]

"""Conformamos un siguiente modelo tomando la estructura de las fechas"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


print("✓ Dataset: ", len(cables_ande_grouped) ," filas cargadas.")
y = cables_ande_grouped["quantity"]
X = cables_ande_grouped[["year_frac"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

"""Visibilizamos la gráfica para ver el proceso"""

plt.figure(figsize=(8, 6))
plt.scatter(y_test, modelo.predict(X_test), color='teal', alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='red', linestyle='--', label='Predicción establecida sobre test')
plt.xlabel('Valor real')
plt.ylabel('Valor predicho')
plt.title('Predicción vs. Valor real')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

mask1 = dataset_cleared['item'].str.contains('Transformador', case=False, na=False)
#mask2 = dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Ampliacion de red electrica', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Servicio desmontaje y montaje de Sistemas electricos de Sub estaciones', case=False, na=False)

serv_transformadores_ande = dataset_cleared[mask1 & mask2]
serv_transformadores_ande.sample(10)

print("Cantidad de registros relacionados con servicios en contratos de ANDE:", len(serv_transformadores_ande))

"""adf"""

serv_transformadores_ande['date_awards'] = pd.to_datetime(serv_transformadores_ande['date_awards'])
serv_transformadores_ande['year_frac'] = serv_transformadores_ande['date_awards'].dt.year + (serv_transformadores_ande['date_awards'].dt.dayofyear - 1) / 365
serv_transformadores_ande = serv_transformadores_ande.sort_values(by=["year_frac", "item"])
#servicios_ande_grouped = serv_transformadores_ande.groupby(['item', 'year_frac', 'currency', 'date_awards'])['quantity'].sum().reset_index()
#servicios_ande_grouped.head()
#servicios_ande_grouped_grouped = servicios_ande_grouped.sort_values(by=["year_frac", "item"])

print("Cantidad de registros relacionados con servicios en contratos de ANDE:", len(serv_transformadores_ande))

resumen_por_año = serv_transformadores_ande.groupby('year_compiled').agg(
    total_items_distintos=('item', 'nunique'),   # cantidad de items únicos ese año
    total_pedidos=('item', 'count'),               # cantidad de registros/pedidos
    cantidad_total=('quantity', 'sum'),
    monto_total=('amount', 'sum')
).reset_index()

print(resumen_por_año)

tabla_montos = serv_transformadores_ande.pivot_table(
    index='item',
    columns='year_compiled',
    values='amount',
    aggfunc='sum',
    fill_value=0
)
print(tabla_montos)

"""adfafd"""

print("✓ Dataset: ", len(serv_transformadores_ande) ," filas cargadas.")
y = serv_transformadores_ande["amount"]
X = serv_transformadores_ande[["year_frac"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

"""agrad"""

plt.figure(figsize=(8, 6))
plt.scatter(y_test, modelo.predict(X_test), color='teal', alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='red', linestyle='--', label='Predicción establecida sobre test')
plt.xlabel('Valor real')
plt.ylabel('Valor predicho')
plt.title('Predicción vs. Valor real')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()