# -*- coding: utf-8 -*-
"""Proyecto_Final_Diplomado_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szgwng7agFB8TX9xg6mpf7u7kMzuNJnL

**Proyecto Final de Diplomado en Machine Learning y Deep Learning Aplicado**

Nombre: Predictor de Compras de Materiales

Datos: Información de Compras Publicas

Etapas del Proceso

1.   Limpieza de los datos recuperados
2.   Verificación de la estructura de los datos
3.   Filtrar por informacion útil
4.   Construcción de Modelo de Regresión

Etapa del modelado ML

1. Analisis Exploratorio
2. Empleo de estategia de Modelo de Regresion
3. Evaluacion de rendimiento
4. Proximas etapas
"""

try:
  from google.colab import drive
  drive.mount('/content/drive/')
  DATA_DIR='/content/drive/MyDrive/Diplomado/Proyecto_Final/contratos'
except ModuleNotFoundError:
  DATA_DIR='.'

print('Entorno OK!')

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

YEAR_LEN = 4

"""Luego de recuperado los archivos, deben obtenerse la relaciones entre si para unificar los procesos.
Existe una relacion entre si teniendo la primera columna relacionada entre los archivos.
Tambien existen referencias dentro de cada archivo a considerar para poder obtener los valores necesarios para el caso de estudio.
Cargar los registros y limpiar uno por uno para generar el dataset de entrenamiento.
"""

# Ejecutar esta celda primero: carga las tablas
for ruta_actual, subdirectorios, archivos in os.walk(DATA_DIR):
  tiene_archivos = any(archivo.endswith('.csv') for archivo in archivos)

  if tiene_archivos:
    # Actualizamos la variable con la última carpeta encontrada
    print(f'Carpeta actual: {ruta_actual}')

    year = ruta_actual[-YEAR_LEN:]
    #print(year)
    for archivo in archivos:
        print(f' - Archivo: {archivo}')

    # leemos los archivos
    contrato = pd.read_csv(ruta_actual+"/parties.csv")
    items = pd.read_csv(ruta_actual+"/awa_items.csv")
    detalles_adj = pd.read_csv(ruta_actual+"/awards.csv")
    print("Adjudicacion (partes):", len(contrato))
    print("Adjudicacion (detalles):", len(detalles_adj))
    print("Items de contratos:", len(items))

    name_filtered_generic = 'data_merged_' + year + '.csv'

    #filtramos los datos importantes por un criterio
    criterio1 = contrato['compiledRelease/parties/0/identifier/legalName'].str.contains('(ANDE)', case=False, na=False)
    criterio2 = contrato['compiledRelease/parties/0/roles'].str.contains('buyer', case=False, na=False)
    contratos_ande = contrato[criterio1 & criterio2]

    # Extraemos columnas especificas de cada dataframe del csv
    columns_to_extract = ["compiledRelease/id", "compiledRelease/parties/0/name"]
    contratos_selected = contratos_ande[columns_to_extract]

    columns_to_extract2 = ["compiledRelease/id", "compiledRelease/awards/0/date"]
    awards_details_selected = detalles_adj[columns_to_extract2]

    # Convert join keys to category
    contratos_selected["compiledRelease/id"] = contratos_selected["compiledRelease/id"].astype('category')
    awards_details_selected["compiledRelease/id"] = awards_details_selected["compiledRelease/id"].astype('category')

    # Merge with better performance
    mixed_awards_contracts = pd.merge(contratos_selected, awards_details_selected, on='compiledRelease/id', how='left')
    mixed_awards_contracts["compiledRelease/year_compiled"] = year

    # deleting dfs to save memory
    del(contrato)
    del(contratos_ande)
    del(contratos_selected)
    del(awards_details_selected)
    del(detalles_adj)

    #Procesa los detalles con los items
    columns_to_extract3 = ["compiledRelease/id", "compiledRelease/awards/0/items/0/classification/description", "compiledRelease/awards/0/items/0/quantity", "compiledRelease/awards/0/items/0/unit/value/amount","compiledRelease/awards/0/items/0/unit/value/currency"]
    items_selected = items[columns_to_extract3]
    items_selected["compiledRelease/id"] = items_selected["compiledRelease/id"].astype('category')
    # merge the columns
    mixed_items_contracts = pd.merge(mixed_awards_contracts, items_selected, on='compiledRelease/id', how='inner')

    mixed_items_contracts.to_csv(ruta_actual+'/'+name_filtered_generic)

    # deleting dfs to save memory
    del(items)
    del(items_selected)
    del(mixed_awards_contracts)
    del(mixed_items_contracts)

print("Listo. Archivos procesados")

"""Luego de procesar por año los conjugamos en uno sólo para reunir los valores"""

df_res = []

for ruta_actual, subdirectorios, archivos in os.walk(DATA_DIR):
  tiene_archivos = any(archivo.endswith('.csv') for archivo in archivos)

  if tiene_archivos:
    # Actualizamos la variable con la última carpeta encontrada -> name_filtered_generic = 'data_merged_' + year + '.csv'
    print(f'Carpeta actual: {ruta_actual}')
    year = ruta_actual[-YEAR_LEN:]
    name_filtered_generic = 'data_merged_' + year + '.csv'

    # leemos los archivos
    adj_contratos = pd.read_csv(ruta_actual+"/"+name_filtered_generic)
    print("Items de contratos:", len(adj_contratos))

    df_res.append(adj_contratos)

final_res = pd.concat(df_res)
print("Listo. Archivos listo para continuar con análisis.")

"""Una vez obteniendo los valores realizamos el filtro de los items mas relevantes"""

print("Items de contratos:", len(final_res))
final_res.sample(5)

"""Guardamos el parcial del analisis para avanzar con consultas sobre el archivo si se requiere."""

final_res.to_csv(DATA_DIR+'/file_filtered_merged.csv')

"""A partir de los datos obtenidos aplicamos filtros para retirar campos que no revisten utilidad y profundizar el analisis de los datos obtenidos y cuales corresponden a nuestro objeto de estudio."""

mask1 = final_res['compiledRelease/parties/0/name'].str.contains('Administración Nacional de Electricidad', case=False, na=False)

datased_cleared = final_res[mask1]

print("Items de contratos - Solo Ande:", len(datased_cleared))
datased_cleared.sample(5)

"""Solamente obtenemos los datos relevantes para mantener un dataset consistente. Para evitar ambigüedad en el filtro anterior sólo retuvimos datos de una entidad.

También procedemos a la extracción de los datos más relevantes y sintéticos posibles a partir del dataset:
- `compiledRelease/awards/0/items/0/classification/description` -> `item`
- `compiledRelease/awards/0/items/0/quantity` -> `quantity`
- `compiledRelease/awards/0/date` -> `date_awards`
- `compiledRelease/awards/0/items/0/unit/value/amount` -> `amount`
- `compiledRelease/awards/0/items/0/unit/value/currency` -> `currency`
- `compiledRelease/year_compiled` -> `year_compiled`

Donde:
1. `item`: es el item realizado en un pedido de licitación
2. `quantity`: cantidad relativa al item
3. `date_awards`: fecha de resolución de la adjudicación para licitación
4. `amount`: monto relativo al item licitado
5. `currency`: moneda relativa al item licitado
6. `year_compiled`: año de compilación del proceso y extraído de los archivos
"""

dataset_cleared = datased_cleared.drop(['compiledRelease/id', 'compiledRelease/parties/0/name', 'Unnamed: 0'], axis=1)
dataset_cleared.rename(columns={'compiledRelease/awards/0/items/0/classification/description': 'item', 'compiledRelease/awards/0/items/0/quantity': 'quantity',
                                 'compiledRelease/awards/0/date': 'date_awards','compiledRelease/awards/0/items/0/unit/value/amount': 'amount',
                                'compiledRelease/awards/0/items/0/unit/value/currency': 'currency', 'compiledRelease/year_compiled': 'year_compiled'}, inplace=True)

"""Una vez obtenido los resultados, verificamos"""

print(dataset_cleared.columns)
dataset_cleared.head()

print("Items de contratos de ANDE:", len(dataset_cleared))

"""Verificamos cuales son los tipo de items solicitados y solo para retener aquellos mas recurrentes"""

#items_mas_pedidos = dataset_cleared["item"].value_counts() #("quantity")
#items_mas_pedidos.head(20)

items_mas_pedidos = (
    dataset_cleared.groupby("year_compiled")["item"]
    .value_counts()  # Cuenta la frecuencia de cada 'item' en cada año
    .reset_index(name="total_items")  # Transforma el resultado en un DataFrame limpio
    .sort_values(
        by=["year_compiled", "total_items"], ascending=[True, False]
    )  # Ordena por año (asc) y cantidad (desc)
)

items_mas_pedidos.head(10)

años = sorted(items_mas_pedidos["year_compiled"].unique())
fig, axes = plt.subplots(1, len(años), figsize=(6*len(años), 6), sharey=False)

if len(años) == 1:
    axes = [axes]

for ax, year in zip(axes, años):
    datos_año = items_mas_pedidos[items_mas_pedidos["year_compiled"] == year].head(10)
    ax.barh(datos_año["item"], datos_año["total_items"], color='steelblue')
    ax.set_title(f'Top items {year}')
    ax.set_xlabel('Cantidad de pedidos')
    ax.invert_yaxis()

plt.tight_layout()
plt.show()

import numpy as np

resumen = dataset_cleared.groupby('item').agg(cantidad=('quantity', 'sum'), monto=('amount', 'sum')).sort_values('cantidad', ascending=False).head(10)

fig, ax1 = plt.subplots(figsize=(10, 6))

x = np.arange(len(resumen))
width = 0.4

ax1.barh(x - width/2, resumen['cantidad'], height=width, color='steelblue', label='Cantidad')
ax1.set_yticks(x)
ax1.set_yticklabels(resumen.index)
ax1.invert_yaxis()
ax1.set_xlabel('Cantidad')

ax2 = ax1.twiny()
ax2.barh(x + width/2, resumen['monto'], height=width, color='darkorange', label='Monto (PYG)')
ax2.set_xlabel('Monto (PYG)')

fig.legend(loc='upper right', bbox_to_anchor=(0.9, 0.9))
plt.title('Top 10 items: Cantidad vs. Monto')
plt.tight_layout()
plt.show()

# Pivotea: filas = item, columnas = year, valores = cantidad
tabla = dataset_cleared.pivot_table(index='item', columns='year_compiled', values='quantity', aggfunc='sum', fill_value=0)

# Tomamos los top 10 items según el total general
top_items = tabla.sum(axis=1).sort_values(ascending=False).head(5).index
tabla = tabla.loc[top_items]

tabla.plot(kind='barh', figsize=(10, 7))
plt.xlabel('Cantidad')
plt.ylabel('Item')
plt.title('Cantidad por item y año')
plt.legend(title='Año')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""Es muy vago y requiere profundidad en un solo objeto"""

mask1 = dataset_cleared['item'].str.contains('Transformador de distribucion', case=False, na=False)
mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Ampliacion de red electrica', case=False, na=False)
#mask1 = dataset_cleared['item'].str.contains('Servicio desmontaje y montaje de Sistemas electricos de Sub estaciones', case=False, na=False)

transformadores_ande = dataset_cleared[mask1 & mask2]
transformadores_ande.sample(10)

#ordenar
transformadores_ande = transformadores_ande.sort_values(by=["year_compiled", "item"])

print("Cantidad de registros de transformadores contratos de ANDE:", len(transformadores_ande))

"""Tratar de obtener el grafico de todo lo obtenido"""

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
plt.scatter(transformadores_ande["year_compiled"], transformadores_ande["quantity"], s=8)
plt.xlabel("Compras de Transformadores de los anhos 2016-2026 (Year_Compiled)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(transformadores_ande["amount"], transformadores_ande["quantity"], s=8)
plt.xlabel("Compras de Transformadores en montos de los anhos 2016-2025 (Year_Compiled)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

# Completar aquí
n_faltantes = transformadores_ande["quantity"].isna().sum()
print("Cantidad de registros faltantes en la columna 'quantity':", n_faltantes)

transformadores_ande.head()

"""Existen muchos valores con cantidades superiores a 3000

Con la informacion obtenida, retiramos los valores para visualizar el cambio
"""

transformadores_ande = transformadores_ande[transformadores_ande["quantity"] <= 3000]
#transformadores_ande = transformadores_ande[transformadores_ande["quantity"] < 2]

transformadores_grouped = transformadores_ande.groupby(['item', 'year_compiled', 'currency'])['quantity'].sum().reset_index()
transformadores_grouped.head()

"""Primer intento:
Generar un modelo de regresion para los datos reorganizados.
"""

print("✓ Dataset: ", len(transformadores_grouped) ," filas cargadas.")
y = transformadores_grouped["quantity"]
X = transformadores_grouped[["year_compiled"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

"""Generamos una pequeña evaluación con datos de test para validar el proceso"""

# Predicciones con lo que haya
# Crear DataFrame con el mismo nombre de columna que X_train
#X_nuevo = pd.DataFrame({"year_compiled": [2026, 2027, 2028]})
y_pred = modelo.predict(X_test)


# evaluamos
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("===== MÉTRICAS DEL MODELO =====")
print(f"MAE  (Error Absoluto Medio): {mae:.3f}")
print(f"RMSE (Raíz del Error Cuadrático Medio): {rmse:.3f}")
print(f"R²   (Coeficiente de Determinación): {r2:.3f}")

"""Verificamos la gráfica para visibilizar el proceso"""

plt.figure(figsize=(8, 6))
plt.scatter(y_test, modelo.predict(X_test), color='teal', alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='red', linestyle='--', label='Predicción establecida sobre test')
plt.xlabel('Valor real')
plt.ylabel('Valor predicho')
plt.title('Predicción vs. Valor real')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""Agregar una validacion pero considerando que tenemos pocos registros... puede ser bajo el rendimiento en especifico para el test"""

from sklearn.model_selection import cross_val_score

# Completar aquí
notas = cross_val_score(LinearRegression(), X, y, cv=5)
print(notas)

nota_honesta = round(notas.mean(), 2)

"""De lo evaluado y con los datos, es muy posible que se tenga muy poco aprendizaje en base al resumen de los datos y las baja cantidad de ocurrencias.

## Segundo Round:
- Ya hemos probado validez con los datos, pero tomemos el ítem de mayor volumen de pedidos
- Arriesguemos tomando los datos de las fechas más largas en el detalle
- Incluso empleemos eso como dato para el año o sólo esa fecha para el modelo
"""

mask1 = dataset_cleared['item'].str.contains('Cable', case=False, na=False)
mask2 = ~dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
mask3 = ~dataset_cleared['item'].str.contains('Montaje', case=False, na=False)
mask4 = ~dataset_cleared['item'].str.contains('Terminación', case=False, na=False)

cables_ande = dataset_cleared[mask1 & mask2 & mask3 & mask4]
cables_ande.sample(10)

"""Como se visibiliza hay muchos datos de fecha con tiempo y no estructura normalizada que debería formatearse."""

# Crear la nueva columna con formato datetime correcto
cables_ande['date_awards'] = pd.to_datetime(cables_ande['date_awards'])
# Convirtamos a un valor medible y diferenciado por año
cables_ande['year_frac'] = cables_ande['date_awards'].dt.year + (cables_ande['date_awards'].dt.dayofyear - 1) / 365
cables_ande_grouped = cables_ande.groupby(['item', 'year_frac', 'currency', 'date_awards'])['quantity'].sum().reset_index()
cables_ande_grouped.head()
cables_ande_grouped = cables_ande_grouped.sort_values(by=["year_frac", "item"])

print("Cantidad de registros de cables en contratos de ANDE:", len(cables_ande_grouped))

cables_ande_grouped.head()

# Ejecutar esta celda (ya está completa): dibuja el primer gráfico del curso
import matplotlib.pyplot as plt

plt.scatter(cables_ande_grouped["year_frac"], cables_ande_grouped["quantity"], s=8)
plt.xlabel("Compras de Cables de los anhos 2016-2026 (Year_Compiled)")
plt.ylabel("Cantidad Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

cables_ande_grouped = cables_ande_grouped[cables_ande_grouped["quantity"] <= 5000]

"""Conformamos un siguiente modelo tomando la estructura de las fechas"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


print("✓ Dataset: ", len(cables_ande_grouped) ," filas cargadas.")
y = cables_ande_grouped["quantity"]
X = cables_ande_grouped[["year_frac"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

"""Visibilizamos la gráfica para ver el proceso"""

plt.figure(figsize=(8, 6))
plt.scatter(y_test, modelo.predict(X_test), color='teal', alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='red', linestyle='--', label='Predicción establecida sobre test')
plt.xlabel('Valor real')
plt.ylabel('Valor predicho')
plt.title('Predicción vs. Valor real')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## Tercer Round:
- Ya hemos probado validez con los datos, pero cambiemos el enfoque a servicios
- Tomemos de vuelta los datos de las fechas más largas en el detalle
"""

mask1 = dataset_cleared['item'].str.contains('Transformador', case=False, na=False)
mask2 = dataset_cleared['item'].str.contains('Servicio', case=False, na=False)
mask3 = dataset_cleared['item'].str.contains('Ampliacion de red electrica', case=False, na=False)
mask4 = dataset_cleared['item'].str.contains('Servicio desmontaje y montaje de Sistemas electricos de Sub estaciones', case=False, na=False)

serv_mant_ande = dataset_cleared[mask1 | mask2 | mask3 | mask4]
serv_mant_ande.sample(10)

print("Cantidad de registros relacionados con servicios en contratos de ANDE:", len(serv_mant_ande))

"""adf"""

# evaluemos el precio de Servicio de poda
mask1 = dataset_cleared['item'].str.contains('Poda', case=False, na=False)
mask2 = dataset_cleared['item'].str.contains('Servicio de Poda', case=False, na=False)

serv_poda_ande = dataset_cleared[mask1 | mask2]
print("Cantidad de registros relacionados con servicios en contratos de ANDE:", len(serv_poda_ande))

# misma estrategia anterior pero para servicios
serv_poda_ande['date_awards'] = pd.to_datetime(serv_poda_ande['date_awards'])
serv_poda_ande['year_frac'] = serv_poda_ande['date_awards'].dt.year + (serv_poda_ande['date_awards'].dt.dayofyear - 1) / 365
serv_poda_ande = serv_poda_ande.sort_values(by=["year_frac", "item"])
serv_poda_ande.sample(10)

"""Se encuentra una mayor consistencia de datos y falta visualizar para estudiar su dispersión."""

plt.scatter(serv_poda_ande["year_frac"], serv_poda_ande["amount"], s=8)
plt.xlabel("Servicios de Poda de los anhos 2016-2025 (Year_Compiled)")
plt.ylabel("Monto de Pedido (Quantity)")
plt.title("Items de contratos: ¿más items = más prevision por anho?")
plt.show()

"""Se pueden eliminar los valores superiores para visualizar el comportamiento en un entrenamiento"""

serv_poda_ande = serv_poda_ande[serv_poda_ande["amount"] <= 10000000000]

"""Luego ya sabemos el camino y realizamos el intento del modelo lineal"""

print("✓ Dataset: ", len(serv_poda_ande) ," filas cargadas.")
y = serv_poda_ande["amount"]
X = serv_poda_ande[["year_frac"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
modelo = LinearRegression()
modelo.fit(X_train, y_train)

datos_entrenamiento = len(X_train)
print("Datos de Entrenamiento = ", datos_entrenamiento)
print("✓ Modelo Terminado. R² =", round(modelo.score(X_test, y_test), 3))

"""Visualizamos el rendimiento en el gráfico para análisis los posibles datos que nos impiden un mejor fit."""

plt.figure(figsize=(8, 6))
plt.scatter(y_test, modelo.predict(X_test), color='teal', alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         color='red', linestyle='--', label='Predicción establecida sobre test')
plt.xlabel('Valor real')
plt.ylabel('Valor predicho')
plt.title('Predicción vs. Valor real')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""Evaluamos su puntaje e intetamos usarlo para predecir"""

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Predicciones con lo que haya
#años_futuros = np.array([[2027], [2028]])
y_pred = modelo.predict(X_test)


# evaluamos
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("===== MÉTRICAS DEL MODELO =====")
print(f"MAE  (Error Absoluto Medio): {mae:.3f}")
print(f"RMSE (Raíz del Error Cuadrático Medio): {rmse:.3f}")
print(f"R²   (Coeficiente de Determinación): {r2:.3f}")

"""Le damos una nota para mejorar nuestras evaluaciones"""

from sklearn.model_selection import cross_val_score

# Completar aquí
notas = cross_val_score(LinearRegression(), X, y, cv=5)
print(notas)

nota_honesta = round(notas.mean(), 2)

"""Merece una prueba al menos para guardar el modelo y emplear un Pipeline"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

# ==== Crear pipeline ====
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

y = serv_poda_ande["amount"]
X = serv_poda_ande[["year_frac"]]

# ==== Entrenar ====
pipeline.fit(X, y)

# ==== Predicciones ====
y_pred = pipeline.predict(X)

# ==== Métricas ====
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print("📊 Métricas del modelo:")
print(f"MAE: {mae:.4f}")
print(f"MSE: {mse:.4f}")
print(f"R² : {r2:.4f}")

# ==== Guardar modelo ====
joblib.dump(pipeline,DATA_DIR+"/modelo_regresion_servicio_poda.pkl")
print("✅ Modelo guardado en 'modelo_regresion_servicio_poda.pkl'")